name: Automatic publication
on:
  # Worflow runs on pull requests where it makes sure that the spec can be
  # generated, that markup and IDL are valid, as well as on pushes to the
  # default branch where it also deploys the generated spec to the gh-pages
  # branch and publishes the result to /TR.
  # The "workflow_dispatch" hook allows repo admins to trigger the workflow
  # manually if needed.
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  main:
    name: Build, validate and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build, validate and deploy spec
        uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: index.html
          DESTINATION: index.html
          GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://github.com/w3c/media-wg/issues/27
          W3C_BUILD_OVERRIDE: |
            specStatus: NOTE
